=== whizsid/whizsid.github.io/schemas/projects-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type":"object",
    "properties": {
        "success":{
            "type":"boolean"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "image":{
            "type": "string"
        },
        "repository": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items":{
                "type": "string"
            }
        },
        "tags":{
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "keywords": {
            "type": "string"
        }
    },
    "required": [
        "success",
        "title",
        "description",
        "repository",
        "languages",
        "tags",
        "keywords"
    ]
}

=== whizsid/whizsid.github.io/data/projects/osm-to-sql.json
{
    "success": true,
    "title": "osm-to-sql",
    "description": "A command line utility to convert open street map to sql.",
    "image": "img/3232.png",
    "repository": "https://github.com/whizsid/osm-to-sql.git",
    "languages": [
        "rust"
    ],
    "tags":["rust"],
    "keywords": "OpenStreet, Map, Converter"
}

=== whizsid/whizsid.github.io/api/projects/osm-to-sql.json
{
    "success": true,
    "title": "osm-to-sql",
    "description": "A command line utility to convert open street map to sql.",
    "image": "logo.png",
    "repository": "https://github.com/whizsid/osm-to-sql.git",
    "languages": [
        "rust"
    ],
    "tags":["rust","php"],
    "keywords": "OpenStreet, Map, Converter"
}

=== whizsid/whizsid.github.io/data/projects/jsonapiunit.json
{
    "success": true,
    "title": "jsonapiunit",
    "description": "A typescript like unit testing tool to test JSON REST APIs.",
    "image": "img/opengraph/projects/jsonapiunit.png",
    "repository": "https://github.com/whizsid/jsonapiunit",
    "languages": [
        "rust"
    ],
    "tags":["unit-testing","cli"],
    "keywords": "Typescript,Unit Testing, JSON, API, Variable Create, Codeless"
}
